name: Build CANgaroo

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git cmake \
          qt6-base-dev qt6-base-private-dev qt6-tools-dev \
          libqt6serialport6-dev libqt6charts6-dev \
          libnl-3-dev libnl-route-3-dev libgl1-mesa-dev

    - name: Run qmake6 and make
      run: |
        qmake6
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: CANgaroo-build
        path: bin/

  build-windows:
    runs-on: windows-latest

    env:
      BUILD_TYPE: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
      
      # Qt 6
      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.1
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          modules: qtserialport qtcharts
          cache: true

     # Qt-Tools in PATH
      - name: Add Qt to PATH
        shell: pwsh
        run: |
          if (-not $env:QT_ROOT_DIR) {
            Write-Error "QT_ROOT_DIR not set"
            exit 1
          }

          "$env:QT_ROOT_DIR\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      # Verifikation (optional, aber empfohlen)
      - name: Verify toolchain
        run: |
          cl
          qmake6 --version

      # qmake
      - name: qmake configure
        run: |
          qmake6 CANgaroo.pro CONFIG+=release

      # Build mit nmake
      - name: Build
        run: |
          nmake

      # Deploy with windeployqt
      - name: Run windeployqt
        shell: pwsh
        run: |
          New-Item -ItemType Directory deploy | Out-Null
          Copy-Item *.exe deploy\

          windeployqt `
            --release `
            --compiler-runtime `
            deploy\CANgaroo.exe

      # Upload
      - name: Upload deployed application
        uses: actions/upload-artifact@v4
        with:
          name: CANgaroo-Windows-Qt6-MSVC
          path: deploy/
